[tool.isort]
profile = "black"
multi_line_output = 3
extend_skip = ["runtests.py", "setup.py"]
skip_gitignore = true
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
src_paths = ["trumbowyg", "tests"]

[tool.black]
target-version = ["py39"]
exclude = '''
(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
    | \.venv
    | runtests.py
    | setup.py
  )
)
'''